Fix issues in retrying the connection to tcp port

diff --git a/mongo/change-stream/Makefile b/mongo/change-stream/Makefile
--- a/mongo/change-stream/Makefile
+++ b/mongo/change-stream/Makefile
@@ -6,10 +6,11 @@ GOBIN := $(GOBASE)/bin
 PROJECT := $(shell basename "$(PWD)")
 SRC := .
 
-CONTAINER = 'Mongo'
+CONTAINER := 'Mongo'
+PORT := 27017
 RETRIES := 5
 SLEEP := 2
-EXTRA_WAIT := 5
+EXTRA_SLEEP := 5
 
 ##@ run-full: Run Mongo container and the Go program
 
@@ -19,11 +20,11 @@ run-full:
 	@docker-compose up > /dev/null 2>&1 &
 	@printf 'Launching $(CONTAINER)'
 	@for i in {1..$(RETRIES)}; \
-		do nc -v -w 1 localhost 6379 > /dev/null 2>&1 && s=0 && break || s=${?} && printf '.' && sleep $(SLEEP); \
+		do nc -v -w 1 localhost $(PORT) > /dev/null 2>&1 && s=0 && break || s=${?} && printf '.' && sleep $(SLEEP); \
 		done; \
-		echo && (exit ${s}) || echo '$(CONTAINER) failed to launch' && echo '$(CONTAINER) up'; \
-		sleep $(EXTRA_WAIT); \
-		go run $(SRC)
+	echo && (exit ${s}) || echo '$(CONTAINER) failed to launch' && echo '$(CONTAINER) up'; \
+	sleep $(EXTRA_SLEEP); \
+	go run $(SRC)
 	@docker-compose down
 
 ##@ run: Run the program
diff --git a/redis/sessions/Makefile b/redis/sessions/Makefile
--- a/redis/sessions/Makefile
+++ b/redis/sessions/Makefile
@@ -6,7 +6,8 @@ GOBIN := $(GOBASE)/bin
 PROJECT := $(shell basename "$(PWD)")
 SRC := .
 
-CONTAINER = 'Redis'
+CONTAINER := 'Redis'
+PORT := 6379
 RETRIES := 5
 SLEEP := 2
 
@@ -18,10 +19,10 @@ run-full:
 	@docker-compose up > /dev/null 2>&1 &
 	@printf 'Launching $(CONTAINER)'
 	@for i in {1..$(RETRIES)}; \
-		do nc -v -w 1 localhost 6379 > /dev/null 2>&1 && s=0 && break || s=${?} && printf '.' && sleep $(SLEEP); \
+		do nc -v -w 1 localhost $(PORT) > /dev/null 2>&1 && s=0 && break || s=${?} && printf '.' && sleep $(SLEEP); \
 		done; \
-		echo && (exit ${s}) || echo '$(CONTAINER) failed to launch' && echo '$(CONTAINER) up'; \
-		go run $(SRC)
+	echo && (exit ${s}) || echo '$(CONTAINER) failed to launch' && echo '$(CONTAINER) up'; \
+	go run $(SRC)
 	@docker-compose down
 
 ##@ run: Run the program
